routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

// ############################# USERS #################################################
// Route::get('/login', 'DashboardController@login')->name('user.login');
// Route::post('/login', 'DashboardController@auth')->name('user.logar');
// Route::get('/logout', 'DashboardController@logout')->name('user.logout');

// ############################# SERVIÇOS ###############################################
Route::resource('servico', 'ServicesController');
Route::get('/servico/user/{user}', 'ServicesController@openService')->name('servico.openService');
Route::get('/showCloseService', 'ServicesController@showCloseService')->name('servico.showCloseService');
Route::get('/closeService', 'ServicesController@closeService')->name('servico.closeService');

// ############################### ROTAS AUTENTICADAS ####################################
Route::middleware('auth')->group(function () {

// ################################ HOME #################################################
    Route::get('/home', 'HomeController@index')->name('home');

// ############################# USUARIOS #################################################
    Route::resource('usuarios', 'UsersController');

// ###################################### MOTORISTA #######################################
    Route::resource('motoristas', 'MotoristasController');

// ############################## ACESSOS #################################################
    Route::resource('acessos', 'RolesController');

// ############################# VIATURAS #################################################
    Route::resource('viaturas', 'ViaturasController');

// ############################# REGISTRO DE SAIDA DE VIATURAS #############################
    Route::resource('registroViaturas', 'RegistroViaturasController');
    Route::get('/registroViatura/corrigir/{registroViaturaOficial}', 'RegistroViaturasController@corrigirRegistroShow')->name('registroViatura.corrigirRegistro');
    Route::put('/registroViatura/{registroViaturaOficial}/update', 'RegistroViaturasController@corrigirRegistroUpdate')->name('registroViatura.corrigirRegistroUpdate');
    Route::any('/dashboard/CmtGda', 'RegistroViaturasController@dashboard')->name('registroViatura.dashboard');

// ############################# REGISTRO DE ENTRADA DE VIATURA ############################
    Route::resource('registroViaturaEntradas', 'RegistroViaturaEntradasController');

// ############################# REGISTRO DE VIATURA OFFICAL ###############################
    Route::get('/registroViaturaOficial', 'RegistroViaturaOficialsController@index')->name('registroViaturaOficial.index');
    Route::get('/registroViaturaOficial/{registroViaturaOficial}', 'RegistroViaturaOficialsController@show')->name('registroViaturaOficial.show');
    Route::put('/registroViaturaOficial/{registroViaturaOficial}/edit', 'RegistroViaturaOficialsController@edit')->name('registroViaturaOficial.edit');
    Route::get('/registroViaturaOficial/finalizarRegistro/{finalizarRegistro}', 'RegistroViaturaOficialsController@finalizarRegistro')->name('registroViaturaOficial.finalizarRegistro');
    Route::get('/trocarCmtGda', 'RegistroViaturaOficialsController@trocarCmtGda')->name('registroViaturaOficial.trocarCmtGda');
    Route::put('/trocarCmtGda/{trocarCmtGda}/update', 'RegistroViaturaOficialsController@trocarCmtGdaUpdate')->name('registroViaturaOficial.trocarCmtGdaUpdate');
    Route::any('/dashboard/ofDia', 'RegistroViaturaOficialsController@dashboard')->name('registroViaturaOficial.dashboard');
    Route::any('/registroViaturaOficial/relatorios/pdf', 'RegistroViaturaOficialsController@viaturasPdf')->name('registroViaturaOficial.viaturasPdf');
    Route::any('/registroViaturaOficial/relatorios/pdf/gerar', 'RegistroViaturaOficialsController@gerarViaturasPdf')->name('registroViaturaOficial.gerarViaturasPdf');

// ######################################### GESTOR #########################################
    Route::get('/dashboard/gestor', 'GestorController@dashboard')->name('gestor.dashboard');
    Route::get('/report/viaturas', 'GestorController@dashboardViaturasPdf')->name('gestor.dashboardViaturasPdf');
    Route::get('/report/viaturas/pdf', 'GestorController@dashboardGerarViaturasPdf')->name('gestor.dashboardGerarViaturasPdf');
    Route::get('/report/viaturas/{report}', 'GestorController@viaturasPdf')->name('gestor.viaturasPdf');
    Route::get('/report/viaturas/pdf/{report}', 'GestorController@gerarViaturasPdf')->name('gestor.gerarViaturasPdf');
    // ################### SERVIÇO ###################
    Route::get('/report/servico', 'GestorController@servico')->name('gestor.reportServico');
    Route::post('/report/servicoShow', 'GestorController@servicoShow')->name('gestor.reportServicoShow');
    Route::post('/report/servicoDataShow', 'GestorController@servicoDataShow')->name('gestor.reportServicoDataShow');
    // ################### SERVIÇO OFICIAL ###################
    Route::get('/report/servico/oficial', 'GestorController@servicoOficial')->name('gestor.reportServicoOficial');
    Route::post('/report/servico/oficialShow', 'GestorController@servicoOficialShow')->name('gestor.reportServicoOficialShow');
    // ################### SERVIÇO CMT GDA ###################
    Route::get('/report/servico/cmtGda', 'GestorController@servicoCmtGda')->name('gestor.reportServicoCmtGda');
    Route::post('/report/servico/cmtGdaShow', 'GestorController@servicoCmtGdaShow')->name('gestor.reportServicoCmtGdaShow');
    // ################### VIATURA ###################
    Route::get('/report/viatura', 'GestorController@viatura')->name('gestor.reportViatura');
    Route::post('/report/viaturaShow', 'GestorController@viaturaShow')->name('gestor.reportViaturaShow');
    Route::post('/report/viaturaDataShow', 'GestorController@viaturaDataShow')->name('gestor.reportViaturaDataShow');
});

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use Caffeinated\Shinobi\Models\Role;
use Caffeinated\Shinobi\Models\Permission;
use App\Services\RolesService;
use App\Http\Requests\RoleCreateRequest;
use App\Http\Requests\RoleUpdateRequest;

class RolesController extends Controller
{
    protected $service;
    public function __construct(RolesService $service)
    {
        $this->middleware('permission::admin');        
        $this->service = $service;
    }

    public function index()
    {
        $roles = Role::all();

        return view('painel.roles.index', compact('roles'));
    }

    public function create()
    {
        $permissions = Permission::get();

        return view('painel.roles.createEdit', compact('permissions'));
    }

    public function store(RoleCreateRequest $request)
    {
        $role = $this->service->store($request);

        session()->flash('success', [
            'success' => $role['success'],
            'messages' => $role['messages'],
        ]);

        return redirect()->route('acessos.index');
    }

    Public function show($id)
    {
        $role = Role::find($id);
        return view('painel.roles.show', compact('role')); 
    }
    
    public function edit($id)
    {
        $role = Role::find($id);
        $permissions = Permission::get();
        
        return view('painel.roles.createEdit', compact('role', 'permissions'));
    }

    public function update(RoleUpdateRequest $request, $id)
    {
        $role = $this->service->update($request, $id);

        session()->flash('success', [
            'success'   => $role['success'],
            'messages'  => $role['messages']
        ]);

        return redirect()->route('acessos.index');
    }

    public function destroy($id)
    {
        $request = $this->service->destroy($id);

        session()->flash('success', [
            'success'   => $request['success'],
            'messages'  => $request['messages'],
        ]);
        
        return redirect()->route('acessos.index');
    }
}

resources/views/painel/roles/createEdit.blade.php
@extends('layouts.mastertop')

@section('content')
<div class="row">
                <div class="col-md-3"></div>
                <div class="col-xs-12 col-md-6">
                        <div id="result"></div>
                        <div class="box box">
                                <div style="background-color: #808000; color:beige" class="box-header with-border">
                                    @if(isset($role))        
                                        <h3><i class="fa fa-unlock"></i> Alterar Perfil de Acesso</h3>
                                        {!! Form::model($role,['route' => ['acessos.update', $role->id], 'method' => 'PUT']) !!}                                        
                                        <h5>Alterar o perfil de acesso.</h5>
                                    @else
                                        <h3><i class="fa fa-unlock"></i> Cadastrar o Perfil de Acesso</h3>
                                        {!! Form::open(['route' => ['acessos.store'], 'method' => 'POST']) !!}
                                        <h5>Cadastrar o perfil de acesso.</h5>
                                    @endif                                    
                                    </div>
                                    @include('layouts.alerts.validationAlert')                               
                                <div class="box-body">
                                    <div class="rows">
                                        <div class="form-group">
                                            <label for="name">Nome: </label>
                                            {!! Form::text('name', $value = null, ['class' => 'form-control', 'autofocus']) !!}
                                        </div>
                                        <div class="form-group">
                                            <label for="slug">Acesso: </label>
                                            @if(isset($role) && $role->id === 1) 
                                            {!! Form::text('slug', $value = null, ['class' => 'form-control', 'readonly' ]) !!}    
                                            @else
                                                {!! Form::text('slug', $value = null, ['class' => 'form-control']) !!}
                                            @endif
                                            
                                        </div>
                                        <div class="form-group">
                                            <label for="description">Descrição: </label>
                                            {!! Form::textarea('description', $value = null, ['class' => 'form-control', 'rows' => '3']) !!}
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="rows">
                                        <h4><i class="fa fa-ulock"></i> Permissão Especial</h4>
                                        <div class="form-group">
                                                <label>{!! Form::radio('special','all-access', null) !!} Acesso Total</label>
                                                @if(isset($role) && $role->id != 1)
                                                    <label>{!! Form::radio('special','no-access', null) !!} Sem Acesso</label>
                                                @else
                                                    <label>{!! Form::radio('special','no-access', null) !!} Sem Acesso</label>
                                                @endif
                                            </div>
                                    </div>
                                    <hr>
                                     <div class="rows">
                                        <h3>Lista de Permissões</h3>  
                                        <ul class="list-unstyled">                                 
                                            @foreach ($permissions as $permission)
                                                <li>    
                                                    <label>
                                                        {!! Form::checkbox('permissions[]', $permission->id, null) !!}
                                                        {{ $permission->name }} - <em>({{ $permission->description }})</em>
                                                    </label>
                                                </li>
                                            @endforeach
                                        </ul>
                                    </div>
                                </div>                                
                                <!-- /.box-body -->
                                <div class="box-footer">
                                    {!! Form::submit(isset($role) ? 'Alterar' : 'Cadastrar', ['class' => 'btn btn-oliva flat']) !!}
                                    <a href="{{ route('acessos.index') }}" class="btn btn-oliva flat">Voltar</a>
                                </div>
                                {!! Form::close() !!}
                        </div><!-- /.box -->
                    </div><!-- /.col -->           
                </div>
@endsection
@push('datatables-css')
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{{ asset('adminlte/plugins/iCheck/all.css') }}">
@endpush

@push('datatables-script')
<!-- iCheck 1.0.1 -->
    <script src="{{ asset('adminlte/plugins/iCheck/icheck.min.js') }}"></script>
@endpush

resources/views/painel/roles/index.blade.php
@extends('layouts.mastertop')

@section('content')
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h3><i class="fa fa-unlock"></i> Cadastro de Perfil de Acesso</h3>
                                Perfis de Acesso para Gerenciamento do Sistema
                                <a class="btn btn-primary btn-flat btn-oliva pull-right"
                                href="{{ route('acessos.create') }}"><i class="fa fa-unlock"></i> Cadastrar Acesso</a>

                            </div>
                            <div class="box-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead class="table_blue">
                                    <tr>
                                        <th>Id</th>
                                        <th>Nome</th>
                                        <th>Acesso</th>
                                        <th>Descrição</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($roles as $role)
                                        <tr>
                                            <td>{{ $role->id }}</td>
                                            <td>{{ $role->name }}</td>
                                            <td>{{ $role->slug }}</td>
                                            <td>{{ $role->description }}</td>
                                            <td style="text-align: center;">
                                                <div style="margin-right:5px" class="btn-group">
                                                    <a href="{{ route('acessos.edit', $role->id) }}"
                                                       data-toggle="tooltip" data-placement="top"
                                                       title="Editar Acessos"><i
                                                                class="fa fa-pencil"></i></a>
                                                </div>
                                                <div style="margin-right:5px" class="btn-group">
                                                    <a href="{{ route('acessos.show', $role->id) }}"
                                                       data-toggle="tooltip" data-placement="top"
                                                       title="Excluir Acesso"> <i
                                                                class='fa fa-trash text-red'></i></a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    </div><!-- /.col -->
                </div><!-- /.row -->            
@endsection

@push('datatables-css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('adminlte/components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush

@push('datatables-script')
    <!-- DataTables -->
    <script src="{{ asset('adminlte/components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('adminlte/components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('pikeadmin/components/popper/popper.min.js') }}"></script>
    <script src="{{ asset('pikeadmin/js/sweetalertsaw.min.js') }}"></script>

    <script>
        $(function () {
            $("#example1").DataTable(
                {
                    "language": {
                        "url": "/adminlte/components/datatables.net/js/ptBr.lang"
                    }
                }
            )
        });
    </script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
            $('[data-toggle="popover"]').popover()
        })
    </script>    
@endpush

resources/views/painel/roles/show.blade.php
@extends('layouts.mastertop')

@section('content')
    <!-- Modal -->
<div class="modal fade custom-modal" data-backdrop="static" id="modal-sucess" tabindex="1" role="dialog" aria-labelledby="customModal" aria-hidden="true">
    <div class="modal-dialog" style="width: 600px">
        <div class="modal-content">
            <div class="modal-header-delete">
                <h3>Excluir Usuário </h3>
            </div>
            <div class="modal-body">  
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box-body">
                            <div class="row">
                                <!-- /.col -->
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label>Nome</label>                                          
                                        <p>{{ $role->name }}</p>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Acesso</label>
                                        <p>{{ $role->slug }}</p>
                                    </div>
                                </div>
                                </div>
                                <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Descrição</label>                                          
                                        <p>{{ $role->description }}</p>
                                    </div>
                                </div>                                
                            </div>                        
                        </div>
                    </div>    
                </div>
            </div>
            <div class="modal-footer">                
                {!! Form::open(['route' => ['acessos.destroy', $role->id], 'method' => 'DELETE']) !!}
                    {!! Form::submit('Excluir', ['class' => 'btn flat btn-danger']) !!}
                    <a href="{{ route('acessos.index') }}" class="btn btn-primary flat">Voltar</a>
                {!! Form::close() !!}                
            </div>      
        </div>
    </div>
</div>		
@endsection

@push('datatables-css')
<!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('pikeadmin/css/style.css') }}">
@endpush

@push('datatables-script')
<!-- DataTables -->
<script src="{{ asset('pikeadmin/components/popper/popper.min.js') }}"></script>
<script>
    $(document).ready(function () {
            $('#modal-sucess').modal('show');
    });    
</script>
@endpush