routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

// ############################# USERS #################################################
// Route::get('/login', 'DashboardController@login')->name('user.login');
// Route::post('/login', 'DashboardController@auth')->name('user.logar');
// Route::get('/logout', 'DashboardController@logout')->name('user.logout');

// ############################# SERVIÇOS ###############################################
Route::resource('servico', 'ServicesController');
Route::get('/servico/user/{user}', 'ServicesController@openService')->name('servico.openService');
Route::get('/showCloseService', 'ServicesController@showCloseService')->name('servico.showCloseService');
Route::get('/closeService', 'ServicesController@closeService')->name('servico.closeService');

// ############################### ROTAS AUTENTICADAS ####################################
Route::middleware('auth')->group(function () {

// ################################ HOME #################################################
    Route::get('/home', 'HomeController@index')->name('home');

// ############################# USUARIOS #################################################
    Route::resource('usuarios', 'UsersController');

// ###################################### MOTORISTA #######################################
    Route::resource('motoristas', 'MotoristasController');

// ############################## ACESSOS #################################################
    Route::resource('acessos', 'RolesController');

// ############################# VIATURAS #################################################
    Route::resource('viaturas', 'ViaturasController');

// ############################# REGISTRO DE SAIDA DE VIATURAS #############################
    Route::resource('registroViaturas', 'RegistroViaturasController');
    Route::get('/registroViatura/corrigir/{registroViaturaOficial}', 'RegistroViaturasController@corrigirRegistroShow')->name('registroViatura.corrigirRegistro');
    Route::put('/registroViatura/{registroViaturaOficial}/update', 'RegistroViaturasController@corrigirRegistroUpdate')->name('registroViatura.corrigirRegistroUpdate');
    Route::any('/dashboard/CmtGda', 'RegistroViaturasController@dashboard')->name('registroViatura.dashboard');

// ############################# REGISTRO DE ENTRADA DE VIATURA ############################
    Route::resource('registroViaturaEntradas', 'RegistroViaturaEntradasController');

// ############################# REGISTRO DE VIATURA OFFICAL ###############################
    Route::get('/registroViaturaOficial', 'RegistroViaturaOficialsController@index')->name('registroViaturaOficial.index');
    Route::get('/registroViaturaOficial/{registroViaturaOficial}', 'RegistroViaturaOficialsController@show')->name('registroViaturaOficial.show');
    Route::put('/registroViaturaOficial/{registroViaturaOficial}/edit', 'RegistroViaturaOficialsController@edit')->name('registroViaturaOficial.edit');
    Route::get('/registroViaturaOficial/finalizarRegistro/{finalizarRegistro}', 'RegistroViaturaOficialsController@finalizarRegistro')->name('registroViaturaOficial.finalizarRegistro');
    Route::get('/trocarCmtGda', 'RegistroViaturaOficialsController@trocarCmtGda')->name('registroViaturaOficial.trocarCmtGda');
    Route::put('/trocarCmtGda/{trocarCmtGda}/update', 'RegistroViaturaOficialsController@trocarCmtGdaUpdate')->name('registroViaturaOficial.trocarCmtGdaUpdate');
    Route::any('/dashboard/ofDia', 'RegistroViaturaOficialsController@dashboard')->name('registroViaturaOficial.dashboard');
    Route::any('/registroViaturaOficial/relatorios/pdf', 'RegistroViaturaOficialsController@viaturasPdf')->name('registroViaturaOficial.viaturasPdf');
    Route::any('/registroViaturaOficial/relatorios/pdf/gerar', 'RegistroViaturaOficialsController@gerarViaturasPdf')->name('registroViaturaOficial.gerarViaturasPdf');

// ######################################### GESTOR #########################################
    Route::get('/dashboard/gestor', 'GestorController@dashboard')->name('gestor.dashboard');
    Route::get('/report/viaturas', 'GestorController@dashboardViaturasPdf')->name('gestor.dashboardViaturasPdf');
    Route::get('/report/viaturas/pdf', 'GestorController@dashboardGerarViaturasPdf')->name('gestor.dashboardGerarViaturasPdf');
    Route::get('/report/viaturas/{report}', 'GestorController@viaturasPdf')->name('gestor.viaturasPdf');
    Route::get('/report/viaturas/pdf/{report}', 'GestorController@gerarViaturasPdf')->name('gestor.gerarViaturasPdf');
    // ################### SERVIÇO ###################
    Route::get('/report/servico', 'GestorController@servico')->name('gestor.reportServico');
    Route::post('/report/servicoShow', 'GestorController@servicoShow')->name('gestor.reportServicoShow');
    Route::post('/report/servicoDataShow', 'GestorController@servicoDataShow')->name('gestor.reportServicoDataShow');
    // ################### SERVIÇO OFICIAL ###################
    Route::get('/report/servico/oficial', 'GestorController@servicoOficial')->name('gestor.reportServicoOficial');
    Route::post('/report/servico/oficialShow', 'GestorController@servicoOficialShow')->name('gestor.reportServicoOficialShow');
    // ################### SERVIÇO CMT GDA ###################
    Route::get('/report/servico/cmtGda', 'GestorController@servicoCmtGda')->name('gestor.reportServicoCmtGda');
    Route::post('/report/servico/cmtGdaShow', 'GestorController@servicoCmtGdaShow')->name('gestor.reportServicoCmtGdaShow');
    // ################### VIATURA ###################
    Route::get('/report/viatura', 'GestorController@viatura')->name('gestor.reportViatura');
    Route::post('/report/viaturaShow', 'GestorController@viaturaShow')->name('gestor.reportViaturaShow');
    Route::post('/report/viaturaDataShow', 'GestorController@viaturaDataShow')->name('gestor.reportViaturaDataShow');
});

app/Http/Controllers/ViaturasController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ViaturasCreateRequest;
use App\Http\Requests\ViaturasUpdateRequest;
use App\Repositories\ViaturasRepository;
use App\Services\ViaturasService;

class ViaturasController extends Controller
{
    protected $repository;
    protected $service;

    public function __construct(ViaturasRepository $repository, ViaturasService $service)
    {
        $this->middleware('permission:ofdia');
        $this->repository   = $repository;
        $this->service      = $service;
    }

    public function index()
    {
        $viaturas = $this->repository->all();

        return view('painel.viaturas.index', [
            'viaturas' => $viaturas
        ]);
    }

    public function create()
    {
        return view('painel.viaturas.createEdit');
    }

    public function store(ViaturasCreateRequest $request)
    {
        $request = $this->service->store($request->all());

        session()->flash('success', [
            'success' => $request['success'],
            'messages' => $request['messages']
        ]);

        return redirect()->route('viaturas.index');
    }

    public function show($id)
    {
        $viatura = $this->repository->find($id);

        return view('painel.viaturas.show', compact('viatura'));
    }

    public function edit($id)
    {
        $viatura = $this->repository->find($id);

        return view('painel.viaturas.createEdit', compact('viatura'));
    }
    public function update(ViaturasUpdateRequest $request, $id)
    {
        $request = $this->service->update($request->all(), $id);

        session()->flash('success', [
            'success'   => $request['success'],
            'messages'  => $request['messages']
        ]);

        return redirect()->route('viaturas.index');
    }

    public function destroy($id)
    {
        $request = $this->service->destroy($id);

        session()->flash('success', [
            'success' => $request['success'],
            'messages' => $request['messages'],
        ]);

        return redirect()->route('viaturas.index');
    }
}

resources/views/painel/viaturas/createEdit.blade.php
@extends('layouts.mastertop')

@section('content')
<div class="row">
                <div class="col-md-3"></div>
                <div class="col-xs-12 col-md-6">
                        <div id="result"></div>
                        <div class="box box">
                                <div style="background-color: #808000; color:beige" class="box-header with-border">
                                        @if(isset($viatura))
                                            <h3><i class="fa fa-car"></i> Alterar Viatura</h3>
                                            {!! Form::model($viatura,['route' => ['viaturas.update', $viatura->id], 'method' => 'put']) !!}
                                        @else
                                            <h3><i class="fa fa-car"></i> Cadastrar Viatura</h3>
                                                {!! Form::open(['route' => 'viaturas.store', 'method' => 'post']) !!}
                                        @endif
                                            <h5>Cadastrar Viaturas da OM.</h5>                                            
                                    </div>                               
                                <div class="box-body">
                                        @include('layouts.alerts.validationAlert')
                                    <div class="form-group">
                                        <label for="prefixo">Prefixo: </label>
                                        {!! Form::text('prefixo', $value = null, ['class' => 'form-control', 'placeholder' => 'Tipo de Viatura', 'autofocus']) !!}
                                    </div>
                                    <div class="form-group">
                                        <label for="ebPlaca">Registro Eb / Placa: </label>
                                        {!! Form::text('eb_placa', $value = null, ['class' => 'form-control', 'placeholder' => 'Registro Eb ou Placa']) !!}
                                    </div>
                                </div>
                                <!-- /.box-body -->
                                <div class="box-footer">
                                    {!! Form::submit(isset($viatura) ? 'Alterar' : 'Cadastrar', ['class' => 'btn btn-oliva flat']) !!}
                                    <a href="{{ route('viaturas.index') }}" class="btn btn-oliva flat">Voltar</a>
                                </div>
                                {!! Form::close() !!}
                        </div><!-- /.box -->
                    </div><!-- /.col -->           
                </div>
@endsection

resources/views/painel/viaturas/index.blade.php
@extends('layouts.mastertop')

@section('content')
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h3><i class="fa fa-car"></i> Cadastro de Viaturas</h3>
                                Viaturas disponiveis na OM
                                <a class="btn btn-primary btn-flat btn-oliva pull-right"
                                   href="{{ route('viaturas.create') }}"><i class="fa fa-car"></i> Cadastrar Viaturas</a>
                            </div>
                            <div class="box-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead class="table_blue">
                                    <tr>
                                        <th>Id</th>
                                        <th>Prefixo</th>
                                        <th>Registro EB / Placa</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($viaturas as $viatura)
                                        <tr>
                                            <td>{{ $viatura->id }}</td>
                                            <td>{{ $viatura->prefixo }}</td>
                                            <td>{{ $viatura->eb_placa }}</td>
                                            <td style="text-align: center;">
                                                <div style="margin-right:5px" class="btn-group">
                                                    <a href="{{ route('viaturas.edit', $viatura->id) }}"
                                                       data-toggle="tooltip" data-placement="top"
                                                       title="Editar {{ $viatura->prefixo }}"><i
                                                                class="fa fa-pencil"></i></a>
                                                </div>
                                                <div style="margin-right:5px" class="btn-group">
                                                    <a href="{{ route('viaturas.show', $viatura->id) }}"
                                                       data-toggle="tooltip" data-placement="top"
                                                       title="Excluir Registro"> <i
                                                                class='fa fa-trash text-red'></i></a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    </div><!-- /.col -->
                </div><!-- /.row -->            
@endsection

@push('datatables-css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('adminlte/components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush

@push('datatables-script')
    <!-- DataTables -->
    <script src="{{ asset('adminlte/components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('adminlte/components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('pikeadmin/components/popper/popper.min.js') }}"></script>
    <script src="{{ asset('pikeadmin/js/sweetalertsaw.min.js') }}"></script>

    <script>
        $(function () {
            $("#example1").DataTable(
                {
                    "language": {
                        "url": "/adminlte/components/datatables.net/js/ptBr.lang"
                    }
                }
            )
        });
    </script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
            $('[data-toggle="popover"]').popover()
        })
    </script>    
@endpush

resources/views/painel/viaturas/show.blade.php
@extends('layouts.mastertop')

@section('content')
    <!-- Modal -->
<div class="modal fade custom-modal" data-backdrop="static" id="modal-sucess" tabindex="1" role="dialog" aria-labelledby="customModal" aria-hidden="true">
    <div class="modal-dialog" style="width: 600px">
        <div class="modal-content">
            <div class="modal-header-delete">
                <h3>Excluir Viatura </h3>
            </div>
            <div class="modal-body">  
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box-body">
                            <div class="row">
                                <!-- /.col -->
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Viatura:</label>                                          
                                        <p>{{ $viatura->prefixo }}</p>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Registro EB / Placa:</label>                                          
                                        <p>{{ $viatura->eb_placa }}</p>
                                    </div>
                                </div>
                            </div>                        
                        </div>
                    </div>    
                </div>
            </div>
            <div class="modal-footer">                
                {!! Form::open(['route' => ['viaturas.destroy', $viatura->id], 'method' => 'DELETE']) !!}
                    {!! Form::submit('Excluir', ['class' => 'btn flat btn-danger']) !!}
                    <a href="{{ route('viaturas.index') }}" class="btn btn-primary flat">Voltar</a>
                {!! Form::close() !!}                
            </div>      
        </div>
    </div>
</div>		
@endsection

@push('datatables-css')
<!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('pikeadmin/css/style.css') }}">
@endpush

@push('datatables-script')
<!-- DataTables -->
<script src="{{ asset('pikeadmin/components/popper/popper.min.js') }}"></script>
<script>
    $(document).ready(function () {
            $('#modal-sucess').modal('show');
    });    
</script>
@endpush