routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

// ############################# USERS #################################################
// Route::get('/login', 'DashboardController@login')->name('user.login');
// Route::post('/login', 'DashboardController@auth')->name('user.logar');
// Route::get('/logout', 'DashboardController@logout')->name('user.logout');

// ############################# SERVIÇOS ###############################################
Route::resource('servico', 'ServicesController');
Route::get('/servico/user/{user}', 'ServicesController@openService')->name('servico.openService');
Route::get('/showCloseService', 'ServicesController@showCloseService')->name('servico.showCloseService');
Route::get('/closeService', 'ServicesController@closeService')->name('servico.closeService');

// ############################### ROTAS AUTENTICADAS ####################################
Route::middleware('auth')->group(function () {

// ################################ HOME #################################################
    Route::get('/home', 'HomeController@index')->name('home');

// ############################# USUARIOS #################################################
    Route::resource('usuarios', 'UsersController');

// ###################################### MOTORISTA #######################################
    Route::resource('motoristas', 'MotoristasController');

// ############################## ACESSOS #################################################
    Route::resource('acessos', 'RolesController');

// ############################# VIATURAS #################################################
    Route::resource('viaturas', 'ViaturasController');

// ############################# REGISTRO DE SAIDA DE VIATURAS #############################
    Route::resource('registroViaturas', 'RegistroViaturasController');
    Route::get('/registroViatura/corrigir/{registroViaturaOficial}', 'RegistroViaturasController@corrigirRegistroShow')->name('registroViatura.corrigirRegistro');
    Route::put('/registroViatura/{registroViaturaOficial}/update', 'RegistroViaturasController@corrigirRegistroUpdate')->name('registroViatura.corrigirRegistroUpdate');
    Route::any('/dashboard/CmtGda', 'RegistroViaturasController@dashboard')->name('registroViatura.dashboard');

// ############################# REGISTRO DE ENTRADA DE VIATURA ############################
    Route::resource('registroViaturaEntradas', 'RegistroViaturaEntradasController');

// ############################# REGISTRO DE VIATURA OFFICAL ###############################
    Route::get('/registroViaturaOficial', 'RegistroViaturaOficialsController@index')->name('registroViaturaOficial.index');
    Route::get('/registroViaturaOficial/{registroViaturaOficial}', 'RegistroViaturaOficialsController@show')->name('registroViaturaOficial.show');
    Route::put('/registroViaturaOficial/{registroViaturaOficial}/edit', 'RegistroViaturaOficialsController@edit')->name('registroViaturaOficial.edit');
    Route::get('/registroViaturaOficial/finalizarRegistro/{finalizarRegistro}', 'RegistroViaturaOficialsController@finalizarRegistro')->name('registroViaturaOficial.finalizarRegistro');
    Route::get('/trocarCmtGda', 'RegistroViaturaOficialsController@trocarCmtGda')->name('registroViaturaOficial.trocarCmtGda');
    Route::put('/trocarCmtGda/{trocarCmtGda}/update', 'RegistroViaturaOficialsController@trocarCmtGdaUpdate')->name('registroViaturaOficial.trocarCmtGdaUpdate');
    Route::any('/dashboard/ofDia', 'RegistroViaturaOficialsController@dashboard')->name('registroViaturaOficial.dashboard');
    Route::any('/registroViaturaOficial/relatorios/pdf', 'RegistroViaturaOficialsController@viaturasPdf')->name('registroViaturaOficial.viaturasPdf');
    Route::any('/registroViaturaOficial/relatorios/pdf/gerar', 'RegistroViaturaOficialsController@gerarViaturasPdf')->name('registroViaturaOficial.gerarViaturasPdf');

// ######################################### GESTOR #########################################
    Route::get('/dashboard/gestor', 'GestorController@dashboard')->name('gestor.dashboard');
    Route::get('/report/viaturas', 'GestorController@dashboardViaturasPdf')->name('gestor.dashboardViaturasPdf');
    Route::get('/report/viaturas/pdf', 'GestorController@dashboardGerarViaturasPdf')->name('gestor.dashboardGerarViaturasPdf');
    Route::get('/report/viaturas/{report}', 'GestorController@viaturasPdf')->name('gestor.viaturasPdf');
    Route::get('/report/viaturas/pdf/{report}', 'GestorController@gerarViaturasPdf')->name('gestor.gerarViaturasPdf');
    // ################### SERVIÇO ###################
    Route::get('/report/servico', 'GestorController@servico')->name('gestor.reportServico');
    Route::post('/report/servicoShow', 'GestorController@servicoShow')->name('gestor.reportServicoShow');
    Route::post('/report/servicoDataShow', 'GestorController@servicoDataShow')->name('gestor.reportServicoDataShow');
    // ################### SERVIÇO OFICIAL ###################
    Route::get('/report/servico/oficial', 'GestorController@servicoOficial')->name('gestor.reportServicoOficial');
    Route::post('/report/servico/oficialShow', 'GestorController@servicoOficialShow')->name('gestor.reportServicoOficialShow');
    // ################### SERVIÇO CMT GDA ###################
    Route::get('/report/servico/cmtGda', 'GestorController@servicoCmtGda')->name('gestor.reportServicoCmtGda');
    Route::post('/report/servico/cmtGdaShow', 'GestorController@servicoCmtGdaShow')->name('gestor.reportServicoCmtGdaShow');
    // ################### VIATURA ###################
    Route::get('/report/viatura', 'GestorController@viatura')->name('gestor.reportViatura');
    Route::post('/report/viaturaShow', 'GestorController@viaturaShow')->name('gestor.reportViaturaShow');
    Route::post('/report/viaturaDataShow', 'GestorController@viaturaDataShow')->name('gestor.reportViaturaDataShow');
});

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\UserCreateRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Repositories\UserRepository;
use App\Entities\User;
use App\Services\UsersService;
use Caffeinated\Shinobi\Models\Role;

class UsersController extends Controller
{
    protected $repository;
    protected $service;

    public function __construct(UserRepository $repository, UsersService $service)
    {
        $this->middleware('permission::admin');
        $this->repository = $repository;
        $this->service = $service;
    }

    public function index()
    {
        $users = $this->repository->all();

        return view('painel.users.index', compact('users'));
    }

    Public function show($id)
    {
        $user = $this->repository->find($id);
        return view('painel.users.show', compact('user')); 
    }
    
    public function edit($id)
    {
        $user = $this->repository->find($id);
        $roles = Role::get();

        return view('painel.users.edit', compact('user', 'roles'));
    }

    public function update(UserUpdateRequest $request, $id)
    {
        $user = $this->service->update($request, $id);

        session()->flash('success', [
            'success'   => $user['success'],
            'messages'  => $user['messages']
        ]);

        return redirect()->route('usuarios.index');
    }

    public function destroy($id)
    {
        $request = $this->service->destroy($id);

        session()->flash('success', [
            'success'   => $request['success'],
            'messages'  => $request['messages'],
        ]);
        
        return redirect()->route('usuarios.index');
    }
}

resources/views/painel/users/edit.blade.php
@extends('layouts.mastertop')

@section('content')
<div class="row">
                <div class="col-md-3"></div>
                <div class="col-xs-12 col-md-6">
                        <div id="result"></div>
                        <div class="box box">
                                <div style="background-color: #808000; color:beige" class="box-header with-border">
                                            <h3><i class="fa fa-car"></i> Alterar Usuário</h3>
                                            {!! Form::model($user,['route' => ['usuarios.update', $user->id], 'method' => 'PUT']) !!}                                        
                                            <h5>Alterar Permissões de Usuários.</h5>                                            
                                    </div>  
                                    @include('layouts.alerts.validationAlert')                             
                                <div class="box-body">                                        
                                    <div class="rows">                                                                                        
                                        <div class="form-group">
                                            <label for="name">Nome: </label>
                                            {!! Form::text('name', $value = null, ['class' => 'form-control', 'autofocus']) !!}
                                        </div>
                                        <div class="form-group">
                                            <label for="username">Login: </label>
                                            {!! Form::text('username', $value = null, ['class' => 'form-control']) !!}
                                        </div>
                                    </div>
                                <hr>
                                    <div class="rows">
                                        <h3>Lista de Acessos</h3>  
                                        <ul class="list-unstyled">                                 
                                            @foreach ($roles as $role)
                                                <li>    
                                                    <label>
                                                        {!! Form::checkbox('roles[]', $role->id, null) !!}
                                                        {{ $role->name }} - <em>({{ $role->description }})</em>
                                                    </label>
                                                </li>
                                            @endforeach
                                        </ul>
                                    </div>
                                </div>                                
                                <!-- /.box-body -->
                                <div class="box-footer">
                                    {!! Form::submit('Alterar', ['class' => 'btn btn-oliva flat']) !!}
                                    <a href="{{ route('usuarios.index') }}" class="btn btn-oliva flat">Voltar</a>
                                </div>
                                {!! Form::close() !!}
                        </div><!-- /.box -->
                    </div><!-- /.col -->           
                </div>
@endsection
@push('datatables-css')
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{{ asset('adminlte/plugins/iCheck/all.css') }}">
@endpush

@push('datatables-script')
<!-- iCheck 1.0.1 -->
    <script src="{{ asset('adminlte/plugins/iCheck/icheck.min.js') }}"></script>
@endpush

resources/views/painel/users/index.blade.php
@extends('layouts.mastertop')

@section('content')
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h3><i class="fa fa-user"></i> Manutenção de Usuários</h3>
                                Usuários Cadastrados no Sistema
                                {{-- <a class="btn btn-primary btn-flat btn-oliva pull-right"
                                href="{{ route('register') }}"><i class="fa fa-user"></i> Cadastrar Usuário</a> --}}
                            </div>
                            <div class="box-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead class="table_blue">
                                    <tr>
                                        <th>Id</th>
                                        <th>Nome</th>
                                        <th>Login</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($users as $user)
                                        <tr>
                                            <td>{{ $user->id }}</td>
                                            <td>{{ $user->name }}</td>
                                            <td>{{ $user->username }}</td>
                                            <td style="text-align: center;">
                                                <div style="margin-right:5px" class="btn-group">
                                                    <a href="{{ route('usuarios.edit', $user->id) }}"
                                                       data-toggle="tooltip" data-placement="top"
                                                       title="Manutenção de Usuários"><i
                                                                class="fa fa-user"></i></a>
                                                </div>
                                                <div style="margin-right:5px" class="btn-group">
                                                    <a href="{{ route('usuarios.show', $user->id) }}"
                                                       data-toggle="tooltip" data-placement="top"
                                                       title="Excluir Usuário"> <i
                                                                class='fa fa-trash text-red'></i></a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    </div><!-- /.col -->
                </div><!-- /.row -->            
@endsection

@push('datatables-css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('adminlte/components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush

@push('datatables-script')
    <!-- DataTables -->
    <script src="{{ asset('adminlte/components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('adminlte/components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('pikeadmin/components/popper/popper.min.js') }}"></script>
    <script src="{{ asset('pikeadmin/js/sweetalertsaw.min.js') }}"></script>

    <script>
        $(function () {
            $("#example1").DataTable(
                {
                    "language": {
                        "url": "/adminlte/components/datatables.net/js/ptBr.lang"
                    }
                }
            )
        });
    </script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
            $('[data-toggle="popover"]').popover()
        })
    </script>    
@endpush

resources/views/painel/users/show.blade.php
@extends('layouts.mastertop')

@section('content')
    <!-- Modal -->
<div class="modal fade custom-modal" data-backdrop="static" id="modal-sucess" tabindex="1" role="dialog" aria-labelledby="customModal" aria-hidden="true">
    <div class="modal-dialog" style="width: 600px">
        <div class="modal-content">
            <div class="modal-header-delete">
                <h3>Excluir Usuário </h3>
            </div>
            <div class="modal-body">  
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box-body">
                            <div class="row">
                                <!-- /.col -->
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Usuário:</label>                                          
                                        <p>{{ $user->name }}</p>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Login</label>                                          
                                        <p>{{ $user->username }}</p>
                                    </div>
                                </div>
                            </div>                        
                        </div>
                    </div>    
                </div>
            </div>
            <div class="modal-footer">                
                {!! Form::open(['route' => ['usuarios.destroy', $user->id], 'method' => 'DELETE']) !!}
                    {!! Form::submit('Excluir', ['class' => 'btn flat btn-danger']) !!}
                    <a href="{{ route('usuarios.index') }}" class="btn btn-primary flat">Voltar</a>
                {!! Form::close() !!}                
            </div>      
        </div>
    </div>
</div>		
@endsection

@push('datatables-css')
<!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('pikeadmin/css/style.css') }}">
@endpush

@push('datatables-script')
<!-- DataTables -->
<script src="{{ asset('pikeadmin/components/popper/popper.min.js') }}"></script>
<script>
    $(document).ready(function () {
            $('#modal-sucess').modal('show');
    });    
</script>
@endpush